### ISSUE TITLE
Does this work with MongoDB?

### ISSUE THREAD

**Issue by drewpotter** [lbdremy/solr-node-client#187]
Hello,

Strange question, does this work with MongoDB as well as more conventional databases?

I have found out how to connect Solr with MongoDB using this; http://blog.mongodb.org/post/29127828146/introducing-mongo-connector

But I want to perform the search in Node.js using your npm module, does this make sense? 

Any help would be appreciated.

**Comment by ColadaFF** [comment]
Hi there,

I don't think I understand your question well, so let's see:

MongoConnector works as a sink from MongoDB to another datasources, the workflow works as follow: 
[MongoDB CRUD Operations] -------> [MongoConnector intercept the operation] ------> [MongoConnector use a custom sink function to pump to another datasource] -----> [Solr Index the document] (For example if your source is solr).

So this module can't affect that flow in any way, so it won't connect to mongodb, since your sink function needs to be write entirely on python and then when documents are on solr, you can query them using this module.

**Comment by drewpotter** [comment]
Cool, thanks. That is what I wanted to know. 

So I can use both together, each doing a different thing. You see I am used to Rails with Sunspot which connects to Solr and takes care of everything, when you are using a normal Database. Only I wanted to try MongoDB.

Thanks for your response!
